version: 0.2

phases:
  install:
    commands:
  pre_build:
    commands:
  build:
    commands:
      # Find the msbuild install path, and save the output as web package zip format
      - '& "C:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe" TransWebAPI.sln /p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true -p:PackageLocation="C:\temp-build\web.zip" /p:OutDir=".\WebIISHostAPI\obj\Release" /verbosity:normal'
      # Install the sonar scanner and specify the version
      - dotnet tool install --global dotnet-sonarscanner --version 4.8.0
      # Define Environment Variable in AWS Codebuild
      - dotnet sonarscanner begin /k:$SONAR_PROJECT_KEY /v:$SONAR_PROJECTVERSION /d:sonar.host.url=$SONAR_HOST /d:sonar.login=$SONAR_LOGIN_KEY /d:sonar.verbose=true
      #- dotnet sonarscanner begin /k:$SONAR_PROJECT_KEY /d:sonar.host.url="$SONAR_HOST" /d:sonar.verbose=true
      - '& "C:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe" TransWebAPI.sln /t:Rebuild'
      - dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
      - dotnet sonarscanner end /d:sonar.login=$SONAR_LOGIN_KEY
  post_build:
    commands: 
      #- aws codecommit post-comment-for-pull-request --pull-request-id $PULL_REQUEST_ID --repository-name $REPOSITORY_NAME --before-commit-id $DESTINATION_COMMIT --after-commit-id $SOURCE_COMMIT --content "Test 2"
